name: Build React on S3
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: s3のバケットを空にする
        working-directory: ./
        run: |
          aws s3 rm s3://${{AWS_S3_BUCKET}} --recursive
      - name: s3にファイルをアップロード
        working-directory: ./
        run: |
          aws s3 cp ./ s3://${{AWS_S3_BUCKET}} --recursive
      - name: CloudFrontのキャッシュをクリア
        working-directory: ./
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ AWS_CLOUDFRONT_ID }} --paths "/*"
