name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: s3のバケットを空にする
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }} --recursive
      - name: s3にファイルをアップロード
        working-directory: ./
        run: |
          aws s3 cp ./ s3://${{ secrets.AWS_S3_BUCKET }}/root --recursive
          aws s3 cp ./ s3://${{ secrets.AWS_S3_BUCKET }}/githuab-actions/whisper-models s3://${{ secrets.AWS_S3_BUCKET }}/root/vendor/whisper/models --recursive
      - name: CloudFrontのキャッシュをクリア
        working-directory: ./
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
